const CARDWIDTH = 250;
const CARDHEIGHT = 400;
const CARDBORDER = 7;
const CARDCOUNTER = 8;
const INCREASMENT = 20;
const RADIUS = 2000;
const ANGLE = 50;

export {
  CARDHEIGHT,
  CARDWIDTH,
  CARDBORDER,
  CARDCOUNTER,
  INCREASMENT,
  RADIUS,
  ANGLE,
};
